CREATE TABLE AREA (ID INTEGER PRIMARY KEY, NAME TEXT, CONTROL_ID INTEGER);
CREATE TABLE CALCULATION (SCENARIOS_IDS TEXT, ID INTEGER PRIMARY KEY, NAME TEXT, OBJECT_ID INTEGER);
CREATE TABLE CALCULATION_CRITERIA (ID INTEGER PRIMARY KEY, CALCULATION_ID INTEGER, CRITERIA_ID INTEGER, K1 TEXT, K2 TEXT, K3 TEXT, ACTUAL_VALUE TEXT, FI TEXT);
CREATE TABLE CONTROL (ID INTEGER PRIMARY KEY, NAME TEXT);
CREATE TABLE CRITERIA (ID INTEGER PRIMARY KEY, NAME TEXT, SIGN TEXT, NPP TEXT, SAFETY_GROUP_ID INTEGER);
CREATE TABLE OBJECT (ID INTEGER PRIMARY KEY, NAME TEXT, UZEL_ID INTEGER, OBJECT_TYPE_ID INTEGER);
CREATE TABLE OBJECT_TYPE (ID INTEGER PRIMARY KEY, NAME TEXT);
CREATE TABLE SAFETY_GROUP (ID INTEGER PRIMARY KEY, NAME TEXT);
CREATE TABLE SCENARIOS (CALCULATION_ID NUMERIC, SCENARIOS_GROUP_ID NUMERIC, ID INTEGER PRIMARY KEY, NAME TEXT, NPP TEXT, OBJECT_TYPE_ID INTEGER);
CREATE TABLE SCENARIOS_CRITERIA (RANK NUMERIC, CALCULATION_ID NUMERIC, ID INTEGER PRIMARY KEY, CRITERIA_ID INTEGER, SCENARIOS_ID INTEGER, CHECKING INTEGER);
CREATE TABLE SCENARIOS_GROUP (ID INTEGER PRIMARY KEY, NAME TEXT);
CREATE TABLE UZEL (ID INTEGER PRIMARY KEY, NAME TEXT, AREA_ID INTEGER);
CREATE TABLE CALCULATION_TABLE (ID INTEGER PRIMARY KEY, CALCULATION_ID INTEGER, SCENARIOS_ID INTEGER, CRITERIA_ID INTEGER, RANG INTEGER, KZNI NUMERIC, UTCHFI NUMERIC, G NUMERIC, D NUMERIC, E1 NUMERIC, E2 NUMERIC, E3 NUMERIC, ENABLE INTEGER);

