


SELECT  S.NPP, C.NAME, C.SIGN, C.SAFETY_GROUP_ID, CC.FI, CT.ID,
  CT.CALCULATION_ID, CT.SCENARIOS_ID, CT.CRITERIA_ID, CT.RANG,
  CT.KZNI, CT.UTCHFI, CT.G, CT.D, CT.E1, CT.E2, CT.E3
  FROM SCENARIOS AS S, CALCULATION_CRITERIA AS CC,
       CRITERIA AS C, CALCULATION_TABLE AS CT
  WHERE C.ID = CT.CRITERIA_ID AND S.ID = CT.SCENARIOS_ID
    AND CC.CALCULATION_ID = CT.CALCULATION_ID AND CC.CRITERIA_ID = CT.CRITERIA_ID
    AND CT.ENABLE = 1 AND CT.CALCULATION_ID = 1

SELECT
  C.ID,
  SC.CRITERIA_ID,
  SC.SCENARIOS_ID
FROM
  SCENARIOS_CRITERIA SC,
  CALCULATION C
WHERE
  SC.CALCULATION_ID = C.ID
  AND SC.CHECKING = 1
  AND like( '%,' || SC.SCENARIOS_ID || ',%', c.SCENARIOS_IDS)=1
  AND SC.CALCULATION_ID = ?

SELECT   C.ID,   SC.CRITERIA_ID,  SC.SCENARIOS_ID
FROM   SCENARIOS_CRITERIA SC,  CALCULATION C
WHERE
  SC.CALCULATION_ID = C.ID
  AND SC.CHECKING = 1
  AND like( '%,' || SC.SCENARIOS_ID || ',%', c.SCENARIOS_IDS)=1
  AND SC.CALCULATION_ID = 1
  
  SELECT  S.NPP, C.NAME, C.SIGN, C.SAFETY_GROUP_ID, CC.FI, CT.ID, CT.CALCULATION_ID, CT.SCENARIOS_ID, CT.CRITERIA_ID, CT.RANG, CT.KZNI, CT.UTCHFI, CT.G, CT.D, CT.E1, CT.E2, CT.E3 FROM SCENARIOS AS S, CALCULATION_CRITERIA AS CC, CRITERIA AS C, CALCULATION_TABLE AS CT WHERE C.ID = CT.CRITERIA_ID AND S.ID = CT.SCENARIOS_ID AND CC.CALCULATION_ID = CT.CALCULATION_ID AND CC.CRITERIA_ID = CT.CRITERIA_ID AND CT.CALCULATION_ID = ? AND CT.ENABLE = 1 ORDER BY CT.SCENARIOS_ID
  
  SELECT o.ID, o.CRITERIA_ID, o.CALCULATION_ID, c.SAFETY_GROUP_ID, c.NAME, c.SIGN, c.NPP, o.K1, o.K2, o.K3, o.ACTUAL_VALUE, o.FI FROM CRITERIA c, CALCULATION_CRITERIA o WHERE c.ID = o.CRITERIA_ID and o.CALCULATION_ID=?
